pipeline {

	stage("Fix the permission issue") {

            agent any

            steps {
                sh "sudo chown root:jenkins /run/docker.sock"
            }

        }
		
    agent {
        docker {
            image 'node:6-alpine'
            args '-p 3000:3000 -u root:root '
        }
    }
    environment {
        CI = 'true'
    }
	
    stages {
        stage('Build') {
            steps {
                sh 'npm install force'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
